### ISSUE TITLE
About the license of this repository

### ISSUE THREAD

**Issue by PINTO0309** [michael-fonder/M4Depth#2]
Thanks for the great work!

I understand that the datasets used are licensed under CC4.0 and cannot be used commercially without special negotiation. What license do you assume for the source code or models committed to this repository of yours?

I'm sure you are busy, so I won't hurry to answer at all.
I'm sure other researchers and engineers are wondering the same thing.

Thank you.

**Comment by michael-fonder** [comment]
Hi @PINTO0309 ,

The delay is outrageously long, but I didn't forget your request. The repository remained largely untouched because we were working on an improved model. I made the improved version public a few weeks ago.

 We now have a clear license on this repository that is the Affero GPLv3.0. You can now use our code within the bounds set by this license.

Best,
Michaël

**Comment by PINTO0309** [comment]
Thanks!
